spring.application.name=avis
spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:avis;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.h2.console.enabled=true
# On definit 3 proprietes necessaires pour echanger avec l'API d'OVH
ovh.application-key=${OVH_APPLICATION_KEY}
ovh.application-secret=${OVH_APPLICATION_SECRET}
ovh.consumer-key=${OVH_CONSUMER_KEY}
logo.dev.publishable-key=${LOGO_DEV_PUBLISHABLE_KEY}
logo.dev.secret-key=${LOGO_DEV_SECRET_KEY}
logo-dev-token=${LOGO_DEV_PUBLISHABLE_KEY}
#server.port=8081
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.file.name=log/avis_log
spring.jpa.properties.hibernate.generate_statistics=true
spring.profiles.active=prod

#---
spring.config.activate.on-profile=dev
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.file.name=log/avis_dev_log
logging.level.org.hibernate.stat=TRACE
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.orm.jpa=DEBUG

#---
spring.config.activate.on-profile=prod
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.file.name=log/avis_prod_log