spring.application.name=avis
spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:~/avis;AUTO_SERVER=TRUE
#spring.h2.console.enabled=true
# On definit 3 proprietes necessaires pour echanger avec l'API d'OVH
ovh.application-key=${OVH_APPLICATION_KEY}
ovh.application-secret=${OVH_APPLICATION_SECRET}
ovh.consumer-key=${OVH_CONSUMER_KEY}
logo.dev.publishable-key=${LOGO_DEV_PUBLISHABLE_KEY}
logo.dev.secret-key=${LOGO_DEV_SECRET_KEY}
logo-dev-token=${LOGO_DEV_TOKEN}
